{
  try {
    call();
  }
 catch (  Exception e) {
    throw new RuntimeException("Exception thrown in call task",e);
  }
  return null;
}
